# .github/workflows/release.yml
name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.0.0

jobs:
  build-and-sign:
    name: Build & Sign (${{ matrix.os }})
    permissions:
      contents: read # Only needs read to checkout
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: amd64
            binary-name: conduit-macos-x64
          - os: macos-latest
            arch: arm64
            binary-name: conduit-macos-arm64
          - os: windows-latest
            arch: amd64
            binary-name: conduit-windows-x64.exe
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # --- macOS Build and Sign ---
      - name: Build macOS Binary
        if: runner.os == 'macOS'
        run: |
          export CGO_ENABLED=1
          export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
          GOOS=darwin GOARCH=${{ matrix.arch }} go build -ldflags="-s -w" -o ${{ matrix.binary-name }} .
          echo "Build complete for ${{ matrix.binary-name }}"

      - name: Sign macOS Binary
        if: runner.os == 'macOS'
        env:
          MACOS_CERT_P12_BASE64: ${{ secrets.MACOS_CERT_P12_BASE64 }}
          MACOS_CERT_PASSWORD: ${{ secrets.MACOS_CERT_PASSWORD }}
          MACOS_SIGNING_IDENTITY: ${{ secrets.MACOS_SIGNING_IDENTITY }}
        run: |
          # Create entitlements file
          echo '<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>com.apple.security.get-task-allow</key><false/></dict></plist>' > entitlements.plist

          # Import certificate from secrets into a temporary keychain
          KEYCHAIN_PATH=$RUNNER_TEMP/app-keychain.keychain-db
          echo -n "${{ env.MACOS_CERT_P12_BASE64 }}" | base64 --decode -o certificate.p12
          security create-keychain -p "${{ env.MACOS_CERT_PASSWORD }}" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "${{ env.MACOS_CERT_PASSWORD }}" $KEYCHAIN_PATH
          security import certificate.p12 -k $KEYCHAIN_PATH -P "${{ env.MACOS_CERT_PASSWORD }}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "${{ env.MACOS_CERT_PASSWORD }}" $KEYCHAIN_PATH

          # Sign binary using the temporary keychain
          codesign --force --timestamp --options runtime \
            --sign "${{ env.MACOS_SIGNING_IDENTITY }}" \
            --entitlements entitlements.plist \
            --keychain $KEYCHAIN_PATH \
            ${{ matrix.binary-name }}
          echo "Successfully signed ${{ matrix.binary-name }}"
      
      # --- Windows Build and Sign ---
      - name: Build Windows Binary
        if: runner.os == 'Windows'
        run: go build -ldflags="-s -w" -o ${{ matrix.binary-name }} .
      
      - name: Sign Windows Binary
        if: runner.os == 'Windows'
        env:
          WINDOWS_PFX_BASE64: ${{ secrets.WINDOWS_CERT_PFX_BASE64 }}
          WINDOWS_PFX_PASSWORD: ${{ secrets.WINDOWS_CERT_PASSWORD }}
        shell: pwsh
        run: |
          # Decode PFX file from secret
          $pfx_cert_b64 = "${{ env.WINDOWS_PFX_BASE64 }}"
          $pfx_path = Join-Path -Path $env:RUNNER_TEMP -ChildPath "cert.pfx"
          [System.IO.File]::WriteAllBytes($pfx_path, [System.Convert]::FromBase64String($pfx_cert_b64))
          
          # Find signtool.exe from the Windows SDK
          $signtool = Get-ChildItem -Path "C:\Program Files (x86)\Windows Kits\10\bin" -Recurse -Filter "signtool.exe" | Where-Object { $_.DirectoryName.Contains("\x64\") } | Select-Object -Last 1 -ExpandProperty FullName
          if (-not $signtool) { Write-Error "signtool.exe not found."; exit 1 }
          
          # Sign the file with a timestamp
          & $signtool sign /f $pfx_path /p "${{ env.WINDOWS_PFX_PASSWORD }}" /tr http://timestamp.digicert.com /td sha256 /fd sha256 "${{ matrix.binary-name }}"
          echo "Successfully signed ${{ matrix.binary-name }}"

      # --- Upload Artifact ---
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.binary-name }}
          path: ${{ matrix.binary-name }}

  release:
    name: Create GitHub Release
    needs: build-and-sign
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create the release
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      
      - name: List downloaded files
        run: find dist -type f -exec ls -l {} +

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
          fail_on_unmatched_files: true